hash-format = "sha256"

[[files]]
file = "LICENSE"
hash = "f051e56494409e7e9249ebeb9c69dc5f4e5493220f4ec63f39be024fcc3fcd5c"

[[files]]
file = "README.md"
hash = "a42c8140bcfa9f07dadec30feab902cb50b5ecf5c78c51656f6c614baaf3835d"

[[files]]
file = "config/Building Gadgets.cfg"
hash = "e15ed6fd9ff4d5a8facc9f4a7fec3db1cb658af7387233d9ca0b3901120cd371"

[[files]]
file = "config/ChickenChunks.cfg"
hash = "d80f93947603aabe6e5706de76e67cefd8420967f01bc65e9f33c7b2c7536585"

[[files]]
file = "config/CustomNpcs.cfg"
hash = "12fc583e3c5d789fb032d1a34bb963908f76f26c28406f072f124f8a30a00f9f"

[[files]]
file = "config/IC2.ini"
hash = "483eac48de8b436889e89ec73ea560c951d9407b35499c3623189c7d24b49fea"

[[files]]
file = "config/MovingWorld/AssemblePriority.cfg"
hash = "27f7494572762747079d39f9e38f42fbbec1bb3b184b1e402d3cc0c69736a529"

[[files]]
file = "config/MovingWorld/Main.cfg"
hash = "8fce17c74e81847dd0fb1f65c1adbe1acbb8cf25b6789471ac45eb46923ac508"

[[files]]
file = "config/ambientsounds-client.json"
hash = "7ab3acfb6a99b9c48935958a46724c79afb04b50d7ac1435129ebf2b136d8ce5"

[[files]]
file = "config/ambientsounds.cfg"
hash = "1d8031997c915e5de106006f25423e9fa33f4258de4cad3b8b4cc6453c1858a9"

[[files]]
file = "config/betterfoliage.cfg"
hash = "f05b6e0b5c333ab6abf5e423003752029f476e242f49aa93b70271c5279c1547"

[[files]]
file = "config/buildcraft/detailed.properties"
hash = "cdb299194ec9b33ce31389f3ac9e7a8cbbe4d433f482376b92cfd5beda90c922"

[[files]]
file = "config/buildcraft/main.cfg"
hash = "93d6758d21643678efea2ca087ef029981e1599eb369f44f31ca2729216a6e50"

[[files]]
file = "config/buildcraft/objects.cfg"
hash = "0e65354b3ff70612a68b2891f31b0a6964254ecf1cf97b4d60e65cf3b4753587"

[[files]]
file = "config/charset/charset.cfg"
hash = "729812a1fb197d3b9c42a34ec517deff0262e2ca3e92a0e2aea4aa6574dc62e8"

[[files]]
file = "config/charset/ids.cfg"
hash = "1df6a2a0915928fe6af5174fbd709ca8e366cf9bf5ab73fd12fc37cdd29f7327"

[[files]]
file = "config/charset/module/lib.cfg"
hash = "8858463624490d50073b9b982bf34dc440b26469854793fd775d17c09e43a285"

[[files]]
file = "config/charset/module/simplelogic.wires.cfg"
hash = "aef36c2c765b1a6f1c65824541697cc70f5896f6351b6b699f134e5fffa82b3b"

[[files]]
file = "config/charset/modules.cfg"
hash = "a0679e923e3fb8102fc69af8bc62c968b389da0314ee061c6174f4b9b93379f8"

[[files]]
file = "config/codechicken/supporters.json"
hash = "17dbbdaf349fe74ceeecfdce8c5e54247ccaf83775749d9194d20d23674540f0"

[[files]]
file = "config/codechicken/supporters.marker"
hash = "96246a81b2d3d3a82d960f7a73ee728e2dec44507a3ffa9a142c4ae746f9ee0e"

[[files]]
file = "config/codechickenlib.cfg"
hash = "1aa05b9dac4c5718764e3e0a4e23addce945ca283dd21959088520160b34a66e"

[[files]]
file = "config/creativecore-client.json"
hash = "5048f62b9c706ff5d54a2f946387a89761058ca47679a76fc8c2f5d82e3642d3"

[[files]]
file = "config/creativecore.json"
hash = "2184d81e4186c0dd1d5537e58e31c05c5a4bb27517f70640ad2f51bc9b243344"

[[files]]
file = "config/davincisvessels.cfg"
hash = "f873e573293410135706934982fc120038236f546a8ccc1f5aeb28b29ddb6315"

[[files]]
file = "config/energyconverters.cfg"
hash = "6041f7867f0e8150415562c318d2c3970f73566fc8f5de1a19cfc8f997fb5976"

[[files]]
file = "config/forestry/apiculture.cfg"
hash = "bf057e56cffe63e7631ffd7bebb28c417de94fa26c5a9816d0d19eb880b47209"

[[files]]
file = "config/forestry/arboriculture.cfg"
hash = "691c290af4051e14cc5fd8c4191785f9f3376454ad7cf7b67f40732129ace271"

[[files]]
file = "config/forestry/backpacks.cfg"
hash = "51d6fdc1d22754dc80e879d30a966c1bba33d5ce5054f74ed9cc594f98b3ce6e"

[[files]]
file = "config/forestry/common.cfg"
hash = "91a9e152b2a4b295454bd31fb2248d6ed2324dec89e93a03852348ea9c94051a"

[[files]]
file = "config/forestry/crates.cfg"
hash = "5862619092e98de013fa18eb2a4a92439f9d098ab85e5951918985a90f41a63a"

[[files]]
file = "config/forestry/farm.cfg"
hash = "1f3433cf5046f56dbb3709282bd2043f0b8700943b737d0d30941f7bc2079c20"

[[files]]
file = "config/forestry/fluids.cfg"
hash = "b3e0ebbf52ef644847953b80508c47356cdb3bce26f4602d4558149dad54eb71"

[[files]]
file = "config/forestry/gamemodes/EASY.cfg"
hash = "199ca40fa3b30900fe6cfc4d2c65b93e08d98c85b2db94041f3d7f142c72a61b"

[[files]]
file = "config/forestry/gamemodes/HARD.cfg"
hash = "29392ba39553f4a94dfa4dccd16237bceeef4514afaddfc1ed756b2274f543a3"

[[files]]
file = "config/forestry/gamemodes/NORMAL.cfg"
hash = "bea2b7556e5cf24b5596e46ca68ff49f26418e4149e07caf3b97be4a84c4db10"

[[files]]
file = "config/forestry/gamemodes/OP.cfg"
hash = "5d76036dbc9cd6a2441ed8dd44b6946b671a4ad4b30fb63e7aa3d0a8e2c5ebe5"

[[files]]
file = "config/forestry/lepidopterology.cfg"
hash = "28362bdf0a5e427e00794bd4568b17b0651df91b507ab3a294669665198bdfe6"

[[files]]
file = "config/forestry/modules.cfg"
hash = "3c4e462d04cd4ecce9f288c8bd5d312863c2ce3b3a7dadd593aea913953037f8"

[[files]]
file = "config/forge.cfg"
hash = "c642d286a0379b2aafd2d282a79239e58d32ac15cc25dfd08bab5747a5d85662"

[[files]]
file = "config/forgeChunkLoading.cfg"
hash = "cdf24d8f911041af84cad64652d648399493c0d713fdaaf08eb7928e6e943efd"

[[files]]
file = "config/fp2.json5"
hash = "b34b355d537bc9a034eb900ae9fb5f86872149644cfd11a5e9a77104c117ef32"

[[files]]
file = "config/immersiveengineering.cfg"
hash = "bde9df5e0a0367ded5a8c4deadec715cc2a1dfea08a6cc5fe9a36b173c3a6934"

[[files]]
file = "config/immersivepetroleum.cfg"
hash = "ce0869c39645a87df66e2d88c569fe7c1eaaca1c2e53f51e281b4379696df2ce"

[[files]]
file = "config/immersiverailroading.cfg"
hash = "921148aa30218333db3b2a34eca262ce0e06cc91093481a7b95fe8e5f08dc46a"

[[files]]
file = "config/immersiverailroading_graphics.cfg"
hash = "99bfabbf5659c811e692f2bacd47b446379bddfb6b9cfefb4d50279e93eb2aea"

[[files]]
file = "config/immersiverailroading_permissions.cfg"
hash = "46a579c263c95df2ab57bbabad32fc92c508c31b21154d9f5d9068633be42276"

[[files]]
file = "config/immersiverailroading_sound.cfg"
hash = "800835e850e5bc7bc0aef360bcb1f56f4ecaf5b8e886fa6435e9da3a25567de9"

[[files]]
file = "config/jei/itemBlacklist.cfg"
hash = "41ab5806db8d5e1c3ce04d36dc8564cc8a21d33dcc0945b3903df0f2a9c68d86"

[[files]]
file = "config/jei/jei.cfg"
hash = "1988985bfeb9100369c6a2f636d401b122f0cf396759f1262fb439c5c29ea367"

[[files]]
file = "config/jei/searchColors.cfg"
hash = "4778e8b2d6b384ac6d52c7ceea96735c62c15bfe80a60e17db76f9f49b4eb8e5"

[[files]]
file = "config/jei/worldSettings.cfg"
hash = "334eb88348263f08519c0cf0d6e64b83db9087599f4bb6d8495c33b3b10b3aac"

[[files]]
file = "config/journeymap_ModInfo.cfg"
hash = "8bca66470d4e2930a9d08e7c7642cff541de450e8f463912f8273c2cee025c51"

[[files]]
file = "config/journeymap_server.cfg"
hash = "bfd7c39f740bf5008fb0dc55e1b140d7436f47c57775f5a0fee9721db56229bc"

[[files]]
file = "config/lunatriuscore.cfg"
hash = "b84215869e85688dfc2e6b8ef1a88e083dca536a2772d7dd5c0defc69210a2cb"

[[files]]
file = "config/mtsconfig.json"
hash = "2ca668ac62eca70dce4dd602f9a0d033411e6f8d7ba52662bad3a7df1c1c641d"

[[files]]
file = "config/mtsconfigclient.json"
hash = "2af5965d3fce56523268b54379d5a6c16c4fb25157549a6efb1e046ef06a439a"

[[files]]
file = "config/opencomputers/default.recipes"
hash = "cef845fe04b23c3395847fdee8cf7133824571d599337a650a16e201e2380bca"

[[files]]
file = "config/opencomputers/gregtech.recipes"
hash = "bba9781865b8cb34cce3ffd04a0a2b531cae7dba27c7d08135de44186b557b2d"

[[files]]
file = "config/opencomputers/hardmode.recipes"
hash = "3cee07211b042b4a926c3b26a86efdcfc4fa74fbf16b95dde33c54f399701d0e"

[[files]]
file = "config/opencomputers/peaceful.recipes"
hash = "5e7873dd3076c0c449d63029170484bd7e1d0340b80eb928a301783530afbe3e"

[[files]]
file = "config/opencomputers/settings.conf"
hash = "5f41932d29dfbb99e5d9c843afa12aa1ff07e142dc2e532b9785ef8e2cd4fb8f"

[[files]]
file = "config/opencomputers/user.recipes"
hash = "5e59679b7d7acb1e1b26f81e6a9a45006fa69811d587805455cc68c7146a4ce9"

[[files]]
file = "config/quark.cfg"
hash = "d844eab17b1c36355455e672bd1144bc5ea8b83536eaa4eace4af78961952240"

[[files]]
file = "config/railstuff.cfg"
hash = "2a37b0a600a7a45509d77bc078cb680062cb90df41237b9c23135ea2c1f523f4"

[[files]]
file = "config/schematica.cfg"
hash = "8867b20fb7c5b9315afa2525b0b410b004c040935d5a14e9b166805733e208f0"

[[files]]
file = "config/splash.properties"
hash = "26615bca033f815ae52beba3fce40e0530e2d3fe4ed13085d81ab916082ad462"

[[files]]
file = "config/trafficcontrol.cfg"
hash = "c89d4fb07877e4e9cbdcef9e87e4ed6a4e683ccce2ef1ee086ce94a59955ac48"

[[files]]
file = "config/treechopper/treechopper.cfg"
hash = "1ceb5dd5dfb64ba80f57a658013f9717bc68c9526ff5dcdced875270a5958fcf"

[[files]]
file = "config/universalmodcore.cfg"
hash = "c45bd5b1e7abf54017883ca37d0d5d1aeb78faa08d26a29c941640ac488afa44"

[[files]]
file = "config/worldedit/worldedit.properties"
hash = "ef10da886e47c883461595c1e2b0756f3574ffc5e53ecb087574d148edf79e9b"

[[files]]
file = "jar/commons0815-1.12.2-1.4.0.jar"
hash = "b8302780b2d234fb686c48b149ea8705291dca2a5f4b252a1e1e1ae3759bef5d"

[[files]]
file = "jar/ocdevices-MC1.12.2-1.0.0-44.jar"
hash = "1028b0db025bea5d6141a6ac26d5f40ef913ffa6890908647f3ff392e7244c70"

[[files]]
file = "mods/ambientsounds.pw.toml"
hash = "f13393c45f4f6be539516a6471a7a94c9b2d5324ecade05f65e9c7c0d2ce0c24"
metafile = true

[[files]]
file = "mods/autoreglib.pw.toml"
hash = "3ae18761d4ed367abd7fadced9ca34cb3d984e8074e273e8f2c2a77bd896c4cc"
metafile = true

[[files]]
file = "mods/better-foliage.pw.toml"
hash = "3eace127e7ad9ba15f8ec724617dd0db163fccea2d6611696bf97a5a57ec2500"
metafile = true

[[files]]
file = "mods/buildcraft.pw.toml"
hash = "1d8c65d141d7bb742e7f471fbc0241b944346318791802ceedc2ef8f61ccecb1"
metafile = true

[[files]]
file = "mods/building-gadgets.pw.toml"
hash = "46979bdaaa6056aa748c6ec2cb5692cf3b4f22e0d9da1aabf13426c1ad241c86"
metafile = true

[[files]]
file = "mods/charset-lib.pw.toml"
hash = "8ca191d1a046fc1ad198ab1dd00fbb1d105e442ceb28f4b467c31b1fdd85bcfd"
metafile = true

[[files]]
file = "mods/chicken-chunks-1-8.pw.toml"
hash = "7535157dd4968defe8fe071bb110aaa6724ce274130cce4d5965f03fe3c59574"
metafile = true

[[files]]
file = "mods/codechicken-lib-1-8.pw.toml"
hash = "09db900f940485fc925d28280350f6476cf65a54dc7cdd54925fb4dc1ea62363"
metafile = true

[[files]]
file = "mods/commons0815.pw.toml"
hash = "a0f083ddcca7e33394cfca7c803409e3d15b13273accff42fe85beecd2ad3d06"
metafile = true

[[files]]
file = "mods/computronics.pw.toml"
hash = "f2920a357620ed30daa2db8309dc86ae28f8cb2b4fdd18c4522e4db1787cd0bb"
metafile = true

[[files]]
file = "mods/crafttweaker.pw.toml"
hash = "1564b6d88d8c6e717597978bba537f3a86ff1c5743aa51cb3c692c5e420822da"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "1ba1f69310fb03a4affcbad852faf7e52ac3363d57825275223de355cdaecc26"
metafile = true

[[files]]
file = "mods/custom-npcs.pw.toml"
hash = "569f43d42b2b3255e7c477bc635472bcf947b84a816aa585c561d1b03b7f532a"
metafile = true

[[files]]
file = "mods/davincis-vessels.pw.toml"
hash = "0ba88f9e5aaf41caa03fff326ad420721f0f4ec1fe780ce0686941dd8eb69092"
metafile = true

[[files]]
file = "mods/energy-converters.pw.toml"
hash = "8d5792c303cfd117cb6aad8443ff6e738245103c0b8985bf0fe640d423f403e2"
metafile = true

[[files]]
file = "mods/engineers-decor.pw.toml"
hash = "179f486abe738fcd39bdf6309e2c8b6523368206273885832a5074e82cb023c1"
metafile = true

[[files]]
file = "mods/forestry.pw.toml"
hash = "23fd651dcbbafe31945780a3e9193f93cd46959b9134e8e9042011d28617f39f"
metafile = true

[[files]]
file = "mods/furenikusroads.pw.toml"
hash = "c6ff5b1fd291f173326a890fcaa819a3befb9c99c075a2c834eb3cd8b142f743"
metafile = true

[[files]]
file = "mods/galacticraft-legacy.pw.toml"
hash = "229e6ddd94256c97d29c601d00872024d34599c37171c60dd7c14a40802f335d"
metafile = true

[[files]]
file = "mods/gyro_heros-helicopter-pack-iv-mts.pw.toml"
hash = "117f5f6771392303504f258ccc8c12acb97a4ef4c1d3645f1071f4a858225606"
metafile = true

[[files]]
file = "mods/immersive-engineering.pw.toml"
hash = "ef6b21e6eb387b52de3a57f66ed65cdd4ba537ccd4b4647006b4cab7ca451263"
metafile = true

[[files]]
file = "mods/immersive-petroleum.pw.toml"
hash = "67eae58ba71d52ec424658ec09b8d384fcced6f41e081fd209e38f5c7c691bf4"
metafile = true

[[files]]
file = "mods/immersive-railroading.pw.toml"
hash = "49df81aa6a91d44b6e796ad01d910af3ad19058807e92c9ce3523c0dddad09a8"
metafile = true

[[files]]
file = "mods/industrial-craft.pw.toml"
hash = "327f292e785699b8c7bee0e5ecf11e4c3aa5d873d902b9af7fc4b778b3d4ff1c"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "e5c1c651f2cfe9abf24bf0dc0b35de22ee48acba3a8b7dee05874f204587b5b1"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "ca8293c39e4d67a700791e0ca974af005752530fdac94b5aae277aad9f688027"
metafile = true

[[files]]
file = "mods/lunatriuscore.pw.toml"
hash = "24cfbe64640f66d4f4e8a963b08e4384b4d10e07068e499f4d4db710bacc3bdb"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "70c9c69d75db4ff890043c66528b3a9e181e2151595f3b45698f1ee3027acd86"
metafile = true

[[files]]
file = "mods/malisiscore.pw.toml"
hash = "1762e88e8d257b32d0d59454f8693e0b33e15d710b5b51b997745a86ce05dc6a"
metafile = true

[[files]]
file = "mods/malisisdoors.pw.toml"
hash = "8eb739e7c584dc301dc8c911d6438dd5064fbd9892c6f6b8d4d0fdec4653361d"
metafile = true

[[files]]
file = "mods/mcmultipart.pw.toml"
hash = "668d769cbc724bdbb4454733b109adcdd9c0ec6f13109f9da8bb7123731ab99d"
metafile = true

[[files]]
file = "mods/minecraft-transport-simulator.pw.toml"
hash = "c423837f378a0e497729ad3d5278165b0e0473acdaf062003e4e3f08e22f2030"
metafile = true

[[files]]
file = "mods/minetweaker-recipemaker.pw.toml"
hash = "b12b80cc10b38169d31684e5c21c7eb7445ec4a53e3e3d8fa8e5fcc64280fad3"
metafile = true

[[files]]
file = "mods/movingworld.pw.toml"
hash = "84f22877452e62523eaacb0e5e00746ec21a4897a507d6ace318c85241cdafb3"
metafile = true

[[files]]
file = "mods/mrcrayfish-furniture-mod.pw.toml"
hash = "a73ddec147ac7a124d4b347d150635dd33c5529499b1d4b0e46cb1d129189d36"
metafile = true

[[files]]
file = "mods/nco-java-legacy-lib.pw.toml"
hash = "18fca6d618dc68ecde404b0eb3c012f5dfda6ae44f98d4f5c9a0cca486c7ec20"
metafile = true

[[files]]
file = "mods/nuclearcraft-overhauled.pw.toml"
hash = "d106a9a350f738df4f532d3b899c501f25f3adcbfce50799caa402aaae055408"
metafile = true

[[files]]
file = "mods/ocdevices.pw.toml"
hash = "a108ab43d7de8edf6ad3f9648b0b6f921322a13bcce4d2f6a1721c671ef3d203"
metafile = true

[[files]]
file = "mods/opencomputers.pw.toml"
hash = "1df0a79d3e3cb7b354acc3eb59981da1e59bb10d60c34e5438df4dff0781a8cb"
metafile = true

[[files]]
file = "mods/opensolidstate.pw.toml"
hash = "cd62fc62c7173e740ec7d7e0d018f49d5f09e62e2416870343f8308c066fd5bf"
metafile = true

[[files]]
file = "mods/quark.pw.toml"
hash = "687c218bd83dd66851f54a329bea6d96e1af46752b73441d06200d7158246a34"
metafile = true

[[files]]
file = "mods/railstuff.pw.toml"
hash = "1dfe7a6cc48770d7197201a12d9d84e5dc180a23dcac2c2d8405c8728daa3574"
metafile = true

[[files]]
file = "mods/redstone-gauges-and-switches.pw.toml"
hash = "623ed2b4068697268c931097333a18adf77f120eebe7206b77afeb07ed62726a"
metafile = true

[[files]]
file = "mods/schematica.pw.toml"
hash = "fd8e67d1e45d6ccb04e0f74334628b21b83e1fe3dad82362ef0ceb66ae9a4369"
metafile = true

[[files]]
file = "mods/shadowfacts-forgelin.pw.toml"
hash = "dfa8447be622af2b2ba871401032e14ec7164212c81193673d6d75194cfcf564"
metafile = true

[[files]]
file = "mods/simplelogic-wires.pw.toml"
hash = "221d18d55959ad779fba93fec88b7f307be1118520c31ea6de91b41589adf5f0"
metafile = true

[[files]]
file = "mods/track-api.pw.toml"
hash = "1aba270d5e75123a91bb61c3d08e61390f1ebf044dfcc53ade325257284b28e6"
metafile = true

[[files]]
file = "mods/traffic-control.pw.toml"
hash = "36be58c5fc18c38ee9804fee11e84db75dcafdb0a6757064ad3029599c0bd105"
metafile = true

[[files]]
file = "mods/transport-simulator-official-vehicle-set.pw.toml"
hash = "6a71efefabf2bb9b681e22339798207c5730c0ec2d2f2e2d51f0377fa5244602"
metafile = true

[[files]]
file = "mods/tree-chopper.pw.toml"
hash = "82ffba699accc238972353bb80ef7acf47324b31fee5feed857da7add808011c"
metafile = true

[[files]]
file = "mods/trinity.pw.toml"
hash = "710765f0c0259dcdb87c044ad18a602d7429a8e8e03bc361b6905a1e776fa345"
metafile = true

[[files]]
file = "mods/universal-mod-core.pw.toml"
hash = "e7ee9764ed3c24afc21cacc6e51aa7b65c4074bb4d78cbb79f429f9640dd1415"
metafile = true

[[files]]
file = "mods/unu-civilian-pack-for-mts.pw.toml"
hash = "8ff1860775c60b752e73443f342735547aa120b654bb1357c0da9e7debc78b85"
metafile = true

[[files]]
file = "mods/unu-parts-pack.pw.toml"
hash = "9c20a07013223509721b2b3d2ca6c54b6d203193aed888c9d8b500b4904b6089"
metafile = true

[[files]]
file = "options.txt"
hash = "63b1de653c241648326c8adb2c8aa0bcc47e3cecca3418c253084e3e15c0a63a"

[[files]]
file = "scripts/oredicts.zs"
hash = "648f22d53c6b0b748fdfd762a8616c9ad5f5dc249257023b2d49f8592e8b3965"

[[files]]
file = "servers.dat"
hash = "2f21c941b89509d6493c541dc7fa7a76f1be014b0891334cdc001f72e4346f80"
